import spark from '../assets/imgs/b1ff20004ad7014e2b5a18d0031f5ce8.jpg'

export const TaxiData = [
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 1
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 2
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 3
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark ,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 4
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 5
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 6
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 7
    },
    {
        title: "Spark",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: spark,
        color: "red",
        price: 12,
        type: "spark",
        number: 998973232,
        name: "Mashina e",
        id: 8
    },
    
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 9
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 10
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 11
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 12
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 13
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 14
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 15
    },
    {
        title: "Cobalt",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://imda.uz/wp-content/uploads/2021/11/cobalt-tashuvchi.jpg",
        color: "white",
        price: 122,
        type: "cobalt",
        number: 23243534543,
        name: "Mashina e",
        id: 16
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 17
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 18
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 19
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 20
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 21
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 22
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 22
    },
    {
        title: "Nexia",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0T-QgrjHFkRUiGjpcQ3g60lQErmqpJo-TwQ&s",
        color: "black",
        price: 22,
        type: "nexia",
        number: 3243424,
        name: "Mashina e",
        id: 23
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 24
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 25
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 26
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 27
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 28
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 29
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 30
    },
    {
        title: "Damas",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://aniq.uz/photos/news/h901VSUFoxeaqKD.jpeg",
        color: "white",
        price: 65,
        type: "damas",
        number: 74332534,
        name: "Mashina e",
        id: 31
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 32
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 33
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 34
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 35
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 36
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 37
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 38
    },
    {
        title: "Tiko",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKO7g5Er2-FuV0qaKvNoNTE2WKzd2Ddgj_8Q&s",
        color: "red",
        price: 7,
        type: "tiko",
        number: 89217498,
        name: "Mashina e",
        id: 39
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 40
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 41
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 42
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 43
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 44
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 45
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 46
    },
    {
        title: "Matiz",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Bpp6csqh0FvdJPLuIhOGg2YOCtvgPhmvlw&s",
        color: "blue",
        price: 23,
        type: "matiz",
        number: 12380230,
        name: "Mashina e",
        id: 47
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 48
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 49
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 50
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 51
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 52
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 53
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 54
    },
    {
        title: "jentra",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCqruA0jDEbnCMyv0w708I1jB9aE2vkkEzKceY1_jZMHTGQqhevPOcgWKLfJ_m0v30No&usqp=CAU",
        color: "black",
        price: 200,
        type: "jentra",
        number: 819389183,
        name: "Mashina e",
        id: 55
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 56
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 57
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 58
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 59
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 60
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 61
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 62
    },
    {
        title: "mers",
        description: "loremn jssj dkdjd sajlkd jlksjf ldjflkdj  lgjflkjljglijlkjfkdjfdjflkdfjoielkskf f fdjflk dflkdsklkfjdl lkdj kjf kdjf djkf kfdk sflkd sj fkdj kfjk fdlkfjdslsj foiejf ldk dsfold jflj flkkjdflk slfjlds flkl ",
        img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/77/d3/ea/vip-cars-available-with.jpg?w=900&h=500&s=1",
        color: "black",
        price: 300,
        type: "mers",
        number: 7681739,
        name: "Mashina e",
        id: 63
    },
    
]